version: '3.6'

services:
  app:
    container_name: "app"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ELASTIC_APM_SERVICE_NAME: "stats"
      ELASTIC_APM_SERVER_URL: "http://apm-server:8200"
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    networks:
      - elastic

  elasticsearch:
    container_name: elasticsearch
    hostname: "elasticsearch"
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic

  kibana:
    container_name: kibana
    hostname: "kibana"
    image: docker.elastic.co/kibana/kibana:$ELASTIC_VERSION
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - kibana:/usr/share/kibana/data
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      - elasticsearch

  apm-server:
    container_name: apm-server
    hostname: "apm-server"
    image: docker.elastic.co/apm/apm-server:$ELASTIC_VERSION
    command: --strict.perms=false -e  # -e flag to log to stderr and disable syslog/file output
    volumes:
      - ./config/apm-server.yml:/usr/share/apm-server/apm-server.yml:ro
    ports:
      - "8200:8200"
    networks:
      - elastic
    depends_on:
      - elasticsearch

  metricbeat:
    container_name: metricbeat
    hostname: "metricbeat"
    image: docker.elastic.co/beats/metricbeat:$ELASTIC_VERSION
    user: root
    volumes:
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - ./config/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - metricbeat:/usr/share/metricbeat/data
    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]
    networks:
      - elastic

volumes:
  elasticsearch:
  kibana:
  metricbeat:

networks:
  elastic:
    driver: bridge