metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "event"
    - "healthcheck"
    - "info"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

- module: golang
  metricsets:
    - expvar
    - heap
  period: 10s
  hosts: ["app:3000"]
  heap.path: "/debug/vars"
  expvar:
    namespace: "example"
    path: "/debug/vars"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  # index: "metricbeat-%{[agent.version]}-%{+yyyy.MM.dd}"

setup.kibana.host: http://kibana:5601